---


# Pacotes Dev

- name: Instalando os pacotes Dev
  apt:
    name: "{{ pacotes_dev }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - dev


# Instalação do Vim

- name: Instalando o Vim
  apt:
    name: vim
    state: present
    update_cache: yes
  become: true
  tags:
    - vim
