---


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - dev
    - vim


# Pacotes Dev

- name: Instalando os pacotes Dev
  apt:
    name: "{{ pacotes_dev }}"
    state: present
  become: true
  tags:
    - dev


# Instalação do Vim

- name: Instalando o Vim
  apt:
    name: vim
    state: present
  become: true
  tags:
    - vim
