---

# Repositorio do Visual Studio Code

- name: Importando a chave do repositorio do Visual Studio Code
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  tags:
    - repo
    - vscode

- name: Adicionando o Repositorio do Visual Studio Code
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
    update_cache: yes
  become: true
  tags:
    - repo
    - vscode
