---

# Pacotes Dev

- name: Instalando os pacotes Dev
  apt:
    name: "{{ pacotes_dev }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - dev
    - nodejs


# Instalação do Vim

- name: Instalando o Vim
  apt:
    name: vim
    state: present
    update_cache: yes
  become: true
  tags:
    - vim
    - editors


# Instalação do Atom

- name: Instalando o Atom
  apt:
    name: atom
    state: present
    update_cache: yes
  become: true
  tags:
    - atom
    - editors


# Instalação do Visual Studio Code

- name: Instalando o Visual Studio Code
  apt:
    name: code
    state: present
    update_cache: yes
  become: true
  tags:
    - editors
    - vscode