---

# Adicionando o repositorio do Atom

- name: Importando a chave do repositorio do Atom
  rpm_key:
    key: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present
  become: true
  tags:
    - repo
    - editors
    - vscode

- name: Copiando arquivo de repositório do Atom
  copy:
    src: atom-rpm.repo
    dest: /etc/yum.repos.d/atom.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - editors
    - vscode


# Adicionando o repositorio do Visual Studio Code

- name: Importando a chave do repositorio do Visual Studio Code
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  tags:
    - repo
    - editors
    - vscode

- name: Copiando arquivo de repositório do Visual Studio Code
  copy:
    src: vscode-rpm.repo
    dest: /etc/yum.repos.d/vscode.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - editors
    - vscode
