---


- name: "Criando estrutura de diretorios para a IDE IntelliJ IDEA => {{ idea_root_dir }}"
  file:
    path: "{{ idea_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0775"
    recurse: yes
  tags:
    - ide
    - directory
    - idea


- name: "Baixando a IDE IntelliJ IDEA Community versão => {{ idea_version }}"
  get_url:
    url: "https://download.jetbrains.com/idea/ideaIC-{{ idea_version }}.tar.gz"
    dest: "{{ idea_root_dir }}"
    timeout: 60
  tags:
    - ide
    - idea


- name: "Extraindo a IDE IntelliJ IDEA Community versão => {{ idea_version }}"
  unarchive:
    src: "{{ idea_root_dir }}/ideaIC-{{ idea_version }}.tar.gz"
    dest: "{{ idea_root_dir }}"
    remote_src: yes
  tags:
    - ide
    - idea


- name: 'Removendo localmente os binários utilizados na instalação da IDE IntelliJ IDEA Community'
  file:
    path: "{{ idea_root_dir }}/ideaIC-{{ idea_version }}.tar.gz"
    state: absent
  tags:
    - ide
    - idea


- name: "Criando estrutura de diretorios para a IDE PyCharm => {{ pycharm_root_dir }}"
  file:
    path: "{{ pycharm_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0775"
    recurse: yes
  tags:
    - ide
    - directory
    - pycharm


- name: "Baixando a IDE PyCharm versão => {{ pycharm_version }}"
  get_url:
    url: "https://download.jetbrains.com/python/pycharm-community-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_root_dir }}"
    timeout: 60
  tags:
    - ide
    - pycharm


- name: "Extraindo a IDE PyCharm versão => {{ pycharm_version }}"
  unarchive:
    src: "{{ pycharm_root_dir }}/pycharm-community-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_root_dir }}"
    remote_src: yes
  tags:
    - ide
    - pycharm


- name: 'Removendo localmente os binários utilizados na instalação da IDE PyCharm'
  file:
    path: "{{ pycharm_root_dir }}/pycharm-community-{{ pycharm_version }}.tar.gz"
    state: absent
  tags:
    - ide
    - pycharm


- name: "Criando estrutura de diretorios para a IDE Eclipse for Enterprise Java Developers => {{ eclipse_root_dir }}"
  file:
    path: "{{ eclipse_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0775"
    recurse: yes
  tags:
    - ide
    - directory
    - eclipse


- name: "Baixando a IDE Eclipse for Enterprise Java Developers Incubation versão => {{ eclipse_version }}"
  when: eclipse_incubation
  get_url:
    url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{ eclipse_version }}/R/eclipse-jee-{{ eclipse_version }}-R-incubation-linux-gtk-x86_64.tar.gz&mirror_id=1"
    dest: "{{ eclipse_root_dir }}"
    timeout: 60
  tags:
    - ide
    - eclipse


- name: "Extraindo a IDE Eclipse for Enterprise Java Developers Incubation versão => {{ eclipse_version }}"
  when: eclipse_incubation
  unarchive:
    src: "{{ eclipse_root_dir }}/eclipse-jee-{{ eclipse_version }}-R-incubation-linux-gtk-x86_64.tar.gz"
    dest: "{{ eclipse_root_dir }}"
    remote_src: yes
  tags:
    - ide
    - eclipse


- name: 'Removendo localmente os binários utilizados na instalação da IDE Eclipse for Enterprise Java Developers Incubation'
  when: eclipse_incubation
  file:
    path: "{{ eclipse_root_dir }}/eclipse-jee-{{ eclipse_version }}-R-incubation-linux-gtk-x86_64.tar.gz"
    state: absent
  tags:
    - ide
    - eclipse


- name: "Baixando a IDE Eclipse for Enterprise Java Developers versão => {{ eclipse_version }}"
  when: not eclipse_incubation
  get_url:
    url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{ eclipse_version }}/R/eclipse-jee-{{ eclipse_version }}-R-linux-gtk-x86_64.tar.gz&mirror_id=1"
    dest: "{{ eclipse_root_dir }}"
    timeout: 60
  tags:
    - ide
    - eclipse


- name: "Extraindo a IDE Eclipse for Enterprise Java Developers versão => {{ eclipse_version }}"
  when: not eclipse_incubation
  unarchive:
    src: "{{ eclipse_root_dir }}/eclipse-jee-{{ eclipse_version }}-R-linux-gtk-x86_64.tar.gz"
    dest: "{{ eclipse_root_dir }}"
    remote_src: yes
  tags:
    - ide
    - eclipse


- name: 'Removendo localmente os binários utilizados na instalação da IDE Eclipse for Enterprise Java Developers'
  when: not eclipse_incubation
  file:
    path: "{{ eclipse_root_dir }}/eclipse-jee-{{ eclipse_version }}-R-linux-gtk-x86_64.tar.gz"
    state: absent
  tags:
    - ide
    - eclipse


- name: "Criando estrutura de diretorios para a IDE Spring Tools => {{ sts_root_dir }}"
  file:
    path: "{{ sts_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0775"
    recurse: yes
  tags:
    - ide
    - directory
    - sts


- name: "Baixando a IDE Spring Tools {{ sts_major_version }} versão => {{ sts_version }}"
  get_url:
    url: "https://download.springsource.com/release/STS{{ sts_major_version }}/{{ sts_version }}/dist/{{ sts_eclipse_version }}/spring-tool-suite-{{ sts_major_version }}-{{ sts_version }}-{{ sts_eclipse_version }}.{{ sts_eclipse_minor_version }}-linux.gtk.x86_64.tar.gz"
    dest: "{{ sts_root_dir }}"
    timeout: 60
  tags:
    - ide
    - sts


- name: "Extraindo a IDE Spring Tools {{ sts_major_version }} versão => {{ sts_version }}"
  unarchive:
    src: "{{ sts_root_dir }}/spring-tool-suite-{{ sts_major_version }}-{{ sts_version }}-{{ sts_eclipse_version }}.{{ sts_eclipse_minor_version }}-linux.gtk.x86_64.tar.gz"
    dest: "{{ sts_root_dir }}"
    remote_src: yes
  tags:
    - ide
    - sts

- name: 'Removendo localmente os binários utilizados na instalação da IDE Spring Tools {{ sts_major_version }}'
  file:
    path: "{{ sts_root_dir }}/spring-tool-suite-{{ sts_major_version }}-{{ sts_version }}-{{ sts_eclipse_version }}.{{ sts_eclipse_minor_version }}-linux.gtk.x86_64.tar.gz"
    state: absent
  tags:
    - ide
    - sts
