---


# Instalando pacotes de Dev

- name: Instalando pacotes de Dev
  zypper:
    name: "{{ pacotes_suse_dev }}"
    state: latest
    update_cache: yes
  become: true
  tags:
    - dev


# Instalando o Vim

- name: Instalando o Vim
  zypper:
    name: vim
    state: latest
    update_cache: yes
  become: true
  tags:
    - vim