---


# Instalando pacotes de Dev

- name: Instalando pacotes de Dev
  zypper:
    name: "{{ pacotes_suse_dev }}"
    state: latest
    force: yes
    oldpackage: yes
  become: true
  tags:
    - dev


# Instalando o Vim

- name: Instalando o Vim
  zypper:
    name: vim
    state: present
    force: yes
  become: true
  tags:
    - vim