---


- name: "Criando estrutura de diretorios para a ferramenta de build Apache Maven 3 => {{ maven_root_dir }}"
  file:
    path: "{{ maven_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775
    recurse: yes
  tags:
    - dev-tools
    - directory
    - maven


- name: "Baixando e extraindo a ferramenta de build Apache Maven 3 versão => {{ maven_version }}"
  unarchive:
    src: "https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_root_dir }}"
    remote_src: yes
  tags:
    - dev-tools
    - maven


- name: "Criando estrutura de diretorios para a ferramenta de build Gradle => {{ gradle_root_dir }}"
  file:
    path: "{{ gradle_root_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775
    recurse: yes
  tags:
    - dev-tools
    - directory
    - gradle


- name: "Baixando e extraindo a ferramenta de build Gradle versão => {{ gradle_version }}"
  unarchive:
    src: "https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip"
    dest: "{{ gradle_root_dir }}"
    remote_src: yes
  tags:
    - dev-tools
    - gradle


- name: 'Atualizando o arquivo .bashrc'
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ bashrc_vars }}"
  tags:
    - dev-tools
    - conf-bashrc
